### PR TITLE
Use native classes in Node.js

### PR DESCRIPTION
**Pull request by taras**
Same as https://github.com/microstates/microstates.js/pull/124

### CODE REVIEW

**Comment by cowboyd** [comment]
So if I understand correctly, only the common js environment will not transpile classes, all others will?

Dumb question, but is this not a problem in the browser as well?

**Comment by taras** [comment]
Yes, it only transpiles for CJS.

In the browser, the assumption is that they’ll be using a transpiler because you have to if you want to support older browsers. 

For people who transpiler for Node, they will need to include cjs files in transpiration. For browser people who don’t transpile for the browser, they’ll need to use the source (somehow)

**Comment by Robdel12** [comment]
> In the browser, the assumption is that they’ll be using a transpiler because you have to if you want to support older browsers.

Does that mean someone is going to have to transpile funcadelic & microstates themselves? Like reach into their `node_modules` folder and transplile?

**Comment by taras** [comment]
No, for the browser, both of these are fully transpiled. The assumption is that they are transpiring their application code as well.

**Comment by wwilsman** [comment]
Can confirm that this allows funcadelic to work in node. Unfortunately, I'm stuck linking to a local microstates which is linked to this branch in order to use microstates at all. 😢 

Could we just merge this for now and in turn update microstates to get it working in node? We can open an issue in both repos to circle back around to native browser classes (if it turns into a problem that people experience).

**Comment by taras** [comment]
Yes, I think that's we should do.

**Comment by cowboyd** [comment]
I'm ok with this. Longer term What about separate built environments files for npm, but still including the source?

```
/index.js # Entry point for raw es7 sources. The goal is to get everybody to eventually use this
/nodule.js # Entry point for node, only modules are transpiled, nothing else.
/nodule/es5.js # Entry point for node, sources transpiled down to es5
/es5.js # Entry point for raw, transpiled es5 sources.
````

And then add an entry point for each use-case.

So if you need to use transpiled node, you would import from "funcadelic/nodule/es5"

**Comment by taras** [comment]
@cowboyd to do what you describe, we'll need to build every one of these versions and distribute all version for each package. Without tree shaking, these extra assets will be included in the user's bundles. This is really messy either way.

**Comment by cowboyd** [comment]
> to do what you describe, we'll need to build every one of these versions and distribute all version for each package. Without tree shaking, these extra assets will be included in the user's bundles. This is really messy either way.

I can see that, but I don't think that these would be included with the bundle would they? AFAIK, tree shaking is about selectively including symbols from a module inside a bundle. But even without tree shaking, a build tool will only include files that are reachable via one of the entry points. These would all be distinct entry points.

Yes it's messy, but it's explicitly messy, and we don't have to provide a one-size-fits-all solution for every possible use-case that when it changes, breaks the other use-cases.

I think it also communicates to consumers "Hey, you really ought to just use the es7 sources, and if you can't then what's up with that?" while still providing them a path forward.

**Comment by taras** [comment]
> But even without tree shaking, a build tool will only include files that are reachable via one of the entry points. These would all be distinct entry points.

It depends. We'll need to think about exactly how this will work, because it'll require some setup.

**Pull request merged**
