### PR TITLE
Support both legacy require & new modules

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
Great lib ❤️. With v0.1.1 users who don't use module loaders need to import this module via `require('funcadelic/cjs')` which is undocumented at the moment. This change doesn't require the user to have this additional knowledge of how this repo works.

It also makes it easy to try out this lib on [runkit](https://runkit.com/npm/funcadelic) when they land on the [funcadelic npm page](https://www.npmjs.com/package/funcadelic).

### CODE REVIEW

**Comment by cowboyd** [comment]
Thanks for this @sivakumar-kailasam! I was wondering what the proper way to support both legacy modules and es modules at the same time was. This is the first time I've see the "module" attribute in the package.json though. Is there some documentation around this convention somewhere?

**Comment by sivakumar-kailasam** [comment]
https://github.com/rollup/rollup/wiki/pkg.module is the closest to an official documentation I've seen in the wild.

**Comment by cowboyd** [comment]
Works for me. Looks like both webpack and rollup support it. Would it make sense to put `jsnext:main` in there since it's mentioned in that document that some folks use it?

**Comment by sivakumar-kailasam** [comment]
we might not need it based on the comments on this issue, https://github.com/jsforum/jsforum/issues/5 (See the note on top or the comment at the end of the thread)

**Pull request merged**
